namespace WILL.WT.PINFORCE
{
    public enum eAlarm
    {
        MOTION_SERVO_ON_TIMEOUT,
        MOTION_ALARM_RESET_TIMEOUT,
        MOTION_GANTRY_TIMEOUT,

        MOTION_SERVO_OFF_AXIS_01,

        MOTION_ALARM_ON_AXIS_01,

        MOTION_MOVE_TIMEOUT_AXIS_Z,

        AUTO_CONTACT_PROC_TIMEOUT,

        LOADCELL_01_OVERWEIGHT,
        LOADCELL_02_OVERWEIGHT,
    }
}
