namespace WILL.WT.PINFORCE.Process.Work.Main
{
    public enum MainStep
    {
        START,

        AUTO_CONTECT_CHECK,

        MOT_AUtO_CONTECT_READY_MOVE_ENTER,
        MOT_AUtO_CONTECT_READY_MOVE_POLLING,

        AUTO_CONTECT_COUNT_SETTTING,

        MOT_AUTO_CONTECT_01_MOVE_ENTER,
        MOT_AUTO_CONTECT_01_MOVE_POLLING,
        MOT_AUTO_CONTECT_01_DELAY,

        MOT_AUTO_CONTECT_02_MOVE_ENTER,
        MOT_AUTO_CONTECT_02_MOVE_POLLING,
        MOT_AUTO_CONTECT_02_DELAY,

        MOT_AUTO_CONTECT_03_MOVE_ENTER,
        MOT_AUTO_CONTECT_03_MOVE_POLLING,
        MOT_AUTO_CONTECT_03_DELAY,

        AUTO_CONTECT_CONUT_CHECK,

        LAST_RELEASE_CHECK,

        MOT_LAST_RELEASE_MOVE_ENTER,
        MOT_LAST_RELEASE_MOVE_POLLING,

        MAIN_START,

        MOT_COL_START_ENTER,
        MOT_COL_START_POLLING,

        END,
    }
}
