namespace WILL.WT.PINFORCE.Process.Work.AutoContect
{
    public enum AutoContectStep
    {
        START,

        MOT_AUtO_CONTECT_READY_MOVE_ENTER,
        MOT_AUtO_CONTECT_READY_MOVE_POLLING,

        COUNT_SETTTING,

        MOT_AUTO_CONTECT_01_MOVE_ENTER,
        MOT_AUTO_CONTECT_01_MOVE_POLLING,
        MOT_AUTO_CONTECT_01_DELAY,

        MOT_AUTO_CONTECT_02_MOVE_ENTER,
        MOT_AUTO_CONTECT_02_MOVE_POLLING,
        MOT_AUTO_CONTECT_02_DELAY,

        MOT_AUTO_CONTECT_03_MOVE_ENTER,
        MOT_AUTO_CONTECT_03_MOVE_POLLING,
        MOT_AUTO_CONTECT_03_DELAY,

        CONUT_CHECK,

        LAST_RELEASE_CHECK,

        MOT_LAST_RELEASE_MOVE_ENTER,
        MOT_LAST_RELEASE_MOVE_POLLING,

        END,
    }
}
